
load(
  "@rules_cc//cc:cc_library.bzl",
  "cc_library",
)

load(
  "@rules_cc//cc:cc_test.bzl",
  "cc_test",
)

package_group(
  name = "clients",
  packages = [
    "//runtime:__subpackages__",
    "//program:__subpackages__",
  ],
)

cc_library(
  name = "basic_interpreter",
  srcs = [
    "basic_interpreter.cc",
    "basic_interpreter.h",
  ],
  visibility = ["//runtime:clients"],
)
