load(
    "@rules_cc//cc:cc_library.bzl",
    "cc_library",
)
load(
    "@rules_cc//cc:cc_test.bzl",
    "cc_test",
)

package_group(
    name = "internal",
    packages = [
        "//algebra/...",
        "//program/...",
    ],
)

package_group(
    name = "clients",
    packages = [
        "//algebra/internal",
        "//examples:__subpackages__",
        "//program:__subpackages__",
    ],
)

cc_library(
    name = "add",
    srcs = [
        "add.h",
    ],
    visibility = [
        "//algebra:clients",
    ],
)

cc_test(
    name = "add_test",
    srcs = [
        "add_test.cc",
    ],
    deps = [
        ":add",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "div",
    srcs = [
        "div.h",
    ],
    visibility = [
        "//algebra:clients",
    ],
)

cc_test(
    name = "div_test",
    srcs = [
        "div_test.cc",
    ],
    deps = [
        ":div",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "literal",
    srcs = [
        "literal.h",
    ],
    visibility = [
        "//algebra:clients",
    ],
)

cc_test(
    name = "literal_test",
    srcs = [
        "literal_test.cc",
    ],
    deps = [
        ":literal",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "mul",
    srcs = [
        "mul.h",
    ],
    visibility = [
        "//algebra:clients",
    ],
)

cc_test(
    name = "mul_test",
    srcs = [
        "mul_test.cc",
    ],
    deps = [
        ":mul",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)

cc_library(
    name = "sub",
    srcs = [
        "sub.h",
    ],
    visibility = [
        "//algebra:clients",
    ],
)

cc_test(
    name = "sub_test",
    srcs = [
        "sub_test.cc",
    ],
    deps = [
        ":sub",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
