
load(
  "@rules_cc//cc:cc_library.bzl",
  "cc_library",
)

load(
  "@rules_cc//cc:cc_test.bzl",
  "cc_test",
)

cc_library(
  name = "add",
  srcs = [
    "add.h",
  ]
)

cc_test(
  name = "add_test",
  srcs = [
    "add_test.cc",
  ],
  deps = [
    ":add",
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_library(
  name = "literal",
  srcs = [
    "literal.h",
  ]
)

cc_test(
  name = "literal_test",
  srcs = [
    "literal_test.cc",
  ],
  deps = [
    ":literal",
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_library(
  name = "mul",
  srcs = [
    "mul.h",
  ]
)

cc_test(
  name = "mul_test",
  srcs = [
    "mul_test.cc",
  ],
  deps = [
    ":mul",
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)

cc_library(
  name = "sub",
  srcs = [
    "sub.h",
  ]
)

cc_test(
  name = "sub_test",
  srcs = [
    "sub_test.cc",
  ],
  deps = [
    ":sub",
    "@googletest//:gtest",
    "@googletest//:gtest_main",
  ]
)