load(
    "@rules_cc//cc:cc_library.bzl",
    "cc_library",
)
load(
    "@rules_cc//cc:cc_test.bzl",
    "cc_test",
)

cc_library(
    name = "runnable",
    srcs = [
        "runnable.h",
    ],
    visibility = ["//visibility:public"],
)

cc_test(
    name = "runnable_test",
    srcs = [
        "runnable_test.cc",
    ],
    deps = [
        ":runnable",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
